# Default, Defaults
markdown: redcarpet
highlighter: pygments # or rouge or null
exclude: ["node_modules", "gulpfile.js", "package.json"]

# Jekyll Defaults
title: Thangka
email: thangkadegelove@gmail.com
description: A small and simple site with huge ideas
baseurl: "http://localhost:3000" # the subpath of your site, e.g. /blog

# Where can people find your site?
url: "http://localhost:3000"
# When developing, set this ^ equal to whatever localhost you're using

# Socail Media links
# Use these to link users to your organization's social media sites
twitter:N/A
facebook:N/A
google:N/A

author: Yolanda Shi
authorBio: Introduce Tibetan culture-Thangka to the world.
